In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

### Load Dataset

In [3]:
df = pd.read_csv('Desktop\\DS Practice\\loan_prediction.csv')
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

### Drop the column 'Loan_ID' as the column doesnt have any impact on loan status

In [5]:
df.drop('Loan_ID', axis = 'columns', inplace=True)

In [6]:
df.head()

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0   Male      No          0      Graduate            No             5849   
1   Male     Yes          1      Graduate            No             4583   
2   Male     Yes          0      Graduate           Yes             3000   
3   Male     Yes          0  Not Graduate            No             2583   
4   Male      No          0      Graduate            No             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0         NaN             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   

  Property_Area Loan_Status  
0         Urban           Y  
1         Rural           N  
2         Urban           Y  
3         Urban           Y  
4         Urban           Y

### Check the number of NaN in the dataset and drop the rows containing NaN

In [7]:
df.isna().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [9]:
df.shape

(614, 12)

In [133]:
df1 = df.dropna()

In [134]:
df1.shape

(480, 12)

In [135]:
df1.isna().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [136]:
df1.head()

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
1   Male     Yes          1      Graduate            No             4583   
2   Male     Yes          0      Graduate           Yes             3000   
3   Male     Yes          0  Not Graduate            No             2583   
4   Male      No          0      Graduate            No             6000   
5   Male     Yes          2      Graduate           Yes             5417   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   
5             4196.0       267.0             360.0             1.0   

  Property_Area Loan_Status  
1         Rural           N  
2         Urban           Y  
3         Urban           Y  
4         Urban           Y  
5         Urban           Y

In [137]:
df1['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [138]:
df1['Married'].unique()

array(['Yes', 'No'], dtype=object)

In [139]:
df1['Education'].unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [140]:
df1['Self_Employed'].unique()

array(['No', 'Yes'], dtype=object)

In [141]:
df1['Credit_History'].unique()

array([1., 0.])

In [142]:
df1['Property_Area'].unique()

array(['Rural', 'Urban', 'Semiurban'], dtype=object)

In [143]:
df1['Loan_Status'].unique()

array(['N', 'Y'], dtype=object)

In [144]:
#Make a copy of df1 to enable replacement without hampering original df
df2 = df1

### Replace Strings in dataset with numerical values

In [145]:
df2['Gender'].replace({'Male' : 1, 'Female' : 0}, inplace=True)   #Replace Male with 1 and Female with 0

df2['Married'].replace({'Yes' : 1, 'No' : 0}, inplace=True)   #If Married is Yes replace with 1 else 0 

df2['Education'].replace({'Graduate' : 1, 'Not Graduate' : 0}, inplace=True)  #If Education is Graduate replace with 1 else 0

df2['Self_Employed'].replace({'Yes' : 1, 'No' : 0}, inplace=True)   #If Self_Employed is Yes replace with 1 else 0

df2['Property_Area'].replace({'Rural' : 0, 'Semiurban' : 1, 'Urban' : 2}, inplace=True) #If Property_Area is rural replace with 0, else if semiurban replace with 1, else 2

df2['Loan_Status'].replace({'Y' : 1, 'N' : 0}, inplace=True) #If Loan_Status is Y replace with 1 else 0

df2.head()

C:\Users\SAK\anaconda3\lib\site-packages\pandas\core\generic.py:6746: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)


Gender  Married Dependents  Education  Self_Employed  ApplicantIncome  \
1       1        1          1          1              0             4583   
2       1        1          0          1              1             3000   
3       1        1          0          0              0             2583   
4       1        0          0          1              0             6000   
5       1        1          2          1              1             5417   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   
5             4196.0       267.0             360.0             1.0   

   Property_Area  Loan_Status  
1              0            0  
2              2            1  
3              2            1  
4              2            1  
5              2            1

In [ ]:
danish = [1, 1, 0, 1, 1, 1000, 0, 66, 360, 1, 2]

In [146]:
df2['Dependents'].replace({'3+' : 3}, inplace=True)

C:\Users\SAK\anaconda3\lib\site-packages\pandas\core\generic.py:6746: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)


In [147]:
df2['Dependents'].unique()

array(['1', '0', '2', 3], dtype=object)

In [148]:
df2['Gender'].astype(float)

df2['Married'].astype(float)

df2['Dependents'].astype(float)

df2['Education'].astype(float)

df2['Self_Employed'].astype(float)

df2['ApplicantIncome'].astype(float)

df2['Property_Area'].astype(float)

df2['Loan_Status'].astype(float)

1      0.0
2      1.0
3      1.0
4      1.0
5      1.0
      ... 
609    1.0
610    1.0
611    1.0
612    1.0
613    0.0
Name: Loan_Status, Length: 480, dtype: float64

In [149]:
x = df2.drop('Loan_Status', axis = 1)

In [150]:
y = df2['Loan_Status']

In [151]:
from sklearn.model_selection import train_test_split

In [197]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.20)

In [198]:
from sklearn.linear_model import LogisticRegression

In [199]:
m = LogisticRegression()

In [200]:
m.fit(x_train, y_train)

C:\Users\SAK\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [201]:
m.score(x_test, y_test)

0.84375

In [206]:
danish = [1, 1, 0, 1, 1, 9000, 0, 90, 360, 1, 2]

In [207]:
m.predict([danish])

array([1], dtype=int64)

In [208]:
m.predict(x_test)

array([1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1], dtype=int64)